import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";

// ─── Auth schema (generated by better-auth) ───
export * from "./auth-schema";

// ─── User profiles ───
export const profiles = sqliteTable("profiles", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull().unique(),
  bio: text("bio"),
  phone: text("phone"),
  country: text("country"),
  timezone: text("timezone"),
  avatarKey: text("avatar_key"),
  role: text("role").notNull().default("customer"), // customer | admin | support
  onboardingStep: integer("onboarding_step").default(0),
  onboardingComplete: integer("onboarding_complete", { mode: "boolean" }).default(false),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

// ─── Enterprise Members (GM-XXXXXXXX IDs) ───
export const members = sqliteTable("members", {
  id: text("id").primaryKey(),           // internal UUID
  userId: text("user_id").notNull().unique(),
  memberId: text("member_id").notNull().unique(), // GM-XXXXXXXX — immutable
  status: text("status").notNull().default("active"), // active | suspended | vip
  tier: text("tier").notNull().default("free"),        // free | starter | premium | elite | enterprise
  joinedAt: integer("joined_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

// ─── Orders ───
export const orders = sqliteTable("orders", {
  id: text("id").primaryKey(),           // ORD-XXXXXXXXX
  userId: text("user_id").notNull(),
  memberId: text("member_id"),           // GM-XXXXXXXX
  productSlug: text("product_slug").notNull(),
  productName: text("product_name").notNull(),
  tier: text("tier").notNull(),          // starter | premium | elite | enterprise
  priceCents: integer("price_cents").notNull(),
  status: text("status").notNull().default("pending"), // pending | processing | completed | failed | refunded
  paymentProvider: text("payment_provider"), // dodo | autumn
  paymentId: text("payment_id"),
  dodoOrderId: text("dodo_order_id"),
  notes: text("notes"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

// ─── Subscriptions ───
export const subscriptions = sqliteTable("subscriptions", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  memberId: text("member_id"),
  planId: text("plan_id").notNull(), // song-starter | song-premium | song-elite | vault-basic | vault-pro | vault-elite | sophia-basic | sophia-pro | sophia-elite | label-creator | label-pro | label-elite
  status: text("status").notNull().default("active"), // active | cancelled | past_due | trialing
  autumnSubscriptionId: text("autumn_subscription_id"),
  currentPeriodEnd: integer("current_period_end", { mode: "timestamp" }),
  cancelAtPeriodEnd: integer("cancel_at_period_end", { mode: "boolean" }).default(false),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

// ─── Productions ───
export const productions = sqliteTable("productions", {
  id: text("id").primaryKey(),           // PROD-XXXXXXXXX
  orderId: text("order_id").notNull(),
  userId: text("user_id").notNull(),
  memberId: text("member_id"),           // GM-XXXXXXXX
  productSlug: text("product_slug").notNull(),
  status: text("status").notNull().default("queued"),
  // queued | story_submitted | media_uploaded | ai_analyzing | ai_complete |
  // music_generating | music_complete | video_generating | video_complete |
  // in_review | revision_requested | delivered | archived
  currentStage: text("current_stage").notNull().default("queued"),
  storyId: text("story_id"),
  deliverableKeys: text("deliverable_keys"),  // JSON array of S3 keys
  revisionCount: integer("revision_count").default(0),
  maxRevisions: integer("max_revisions").default(1),
  estimatedDeliveryAt: integer("estimated_delivery_at", { mode: "timestamp" }),
  deliveredAt: integer("delivered_at", { mode: "timestamp" }),
  notes: text("notes"),
  metadata: text("metadata"),  // JSON
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

// ─── Acknowledgements ───
export const acknowledgements = sqliteTable("acknowledgements", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  memberId: text("member_id"),
  productSlug: text("product_slug").notNull(),
  acknowledgedAt: integer("acknowledged_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  ip: text("ip"),
  userAgent: text("user_agent"),
  // Unique per user+product — one acknowledgement per product
});

// ─── Story submissions ───
export const stories = sqliteTable("stories", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  memberId: text("member_id"),
  orderId: text("order_id"),
  productionId: text("production_id"),
  title: text("title"),
  storyText: text("story_text").notNull(),
  emotion: text("emotion"), // joy | grief | love | nostalgia | pride | hope | etc
  style: text("style"),     // cinematic | acoustic | orchestral | hip-hop | etc
  mood: text("mood"),
  goals: text("goals"),
  aiAnalysis: text("ai_analysis"),  // JSON blob
  lyrics: text("lyrics"),
  script: text("script"),
  storyboard: text("storyboard"),   // JSON blob
  status: text("status").notNull().default("draft"), // draft | analyzing | analyzed | in_production | complete
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

// ─── Media assets ───
export const assets = sqliteTable("assets", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  storyId: text("story_id"),
  orderId: text("order_id"),
  productionId: text("production_id"),
  type: text("type").notNull(), // photo | video | voice | document | song | generated_video
  key: text("key").notNull(),   // S3/Tigris key
  filename: text("filename").notNull(),
  contentType: text("content_type").notNull(),
  sizeBytes: integer("size_bytes"),
  metadata: text("metadata"),   // JSON
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

// ─── AI jobs ───
export const aiJobs = sqliteTable("ai_jobs", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  orderId: text("order_id"),
  productionId: text("production_id"),
  storyId: text("story_id"),
  type: text("type").notNull(), // emotion_analysis | lyrics | script | storyboard | music_gen | video_gen | image_gen
  provider: text("provider"),   // openai | poyo | fal | modal | vastai
  externalJobId: text("external_job_id"),
  status: text("status").notNull().default("queued"), // queued | running | completed | failed
  input: text("input"),   // JSON
  output: text("output"), // JSON
  errorMessage: text("error_message"),
  durationMs: integer("duration_ms"),
  costCents: integer("cost_cents"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

// ─── Sophia AI companion conversations ───
export const conversations = sqliteTable("conversations", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  title: text("title"),
  messages: text("messages").notNull().default("[]"), // JSON array
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

// ─── Support tickets ───
export const tickets = sqliteTable("tickets", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  memberId: text("member_id"),
  subject: text("subject").notNull(),
  body: text("body").notNull(),
  status: text("status").notNull().default("open"), // open | in_progress | resolved | closed
  priority: text("priority").notNull().default("normal"), // low | normal | high | urgent
  assignedTo: text("assigned_to"),
  messages: text("messages").notNull().default("[]"), // JSON array
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});

// ─── Audit logs ───
export const auditLogs = sqliteTable("audit_logs", {
  id: text("id").primaryKey(),
  userId: text("user_id"),
  memberId: text("member_id"),
  action: text("action").notNull(),
  // Actions: member.created | product.acknowledged | product.viewed | product.purchased
  //          onboarding.started | onboarding.step_completed | onboarding.completed
  //          story.submitted | media.uploaded | ai.job_started | ai.job_completed
  //          payment.initiated | payment.completed | payment.failed | payment.refunded
  //          production.created | production.stage_updated | production.delivered
  //          account.created | account.signin | account.signout | account.suspended
  entity: text("entity"),     // member | order | production | story | asset | subscription
  entityId: text("entity_id"),
  metadata: text("metadata"), // JSON
  ip: text("ip"),
  userAgent: text("user_agent"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});
